### ISSUE TITLE
Maybe a redundant code

### ISSUE THREAD

**Issue by teabroker** [azu/events-to-async#8]
It seems like there is some incorrectness in the code of `onAbort` function (at [src/events-to-async.ts:119](https://github.com/azu/events-to-async/blob/main/src/events-to-async.ts#L119)). It removes `offListener` from the `abort` event listeners. But there is no corresponding `addEventListener` call with `offListener` as an argument.

**Comment by azu** [comment]
Thanks!

Fixed in https://github.com/azu/events-to-async/releases/tag/v2.0.1
